version: "3"

services:

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: vocablens
      POSTGRES_PASSWORD: vocablens
      POSTGRES_DB: vocablens
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A vocablens.worker worker --loglevel=info
    depends_on:
      - redis
      - postgres